/**
 * This file contains the skills section of the resume.
 * @dependency None
 * @exports SKILLS_DATA - Array of skill objects for resume
 */

export const SKILLS_DATA = [
  // Software Engineer
  { id: "languages",
    type: "default",
    label: "Languages",
    text: "Python, SQL, JavaScript & TypeScript, Java, Bash, PL/SQL, AWS CLI",
  },
  { id: "backend",
    type: "default",
    label: "Backend",
    text: "Spring Boot, FastAPI, Flask, AWS Lambda, REST, Async Design, Threading & Parallelism",
  },
  { id: "frontend",
    type: "default",
    label: "Web & Security",
    text: "React, AWS API Gateway, OpenAPI, OAuth2.0, OIDC, JWT, Selenium",
  },
  { id: "cloud_infrastructure",
    type: "default",
    label: "Infrastructure",
    text: "Linux, Docker, AWS (SAM (IaC), CloudFront, S3, IAM, VPC, RDS), Rundeck Automation",
  },
  { id: "data_persistence",
    type: "default",
    label: "Data",
    text: "PostgreSQL, Oracle, AWS (DynamoDB, MariaDB, SQS, SNS), JMS, ORM (Hibernate, SQLAlchemy)",
  },
  { id: "tools_devops",
    type: "default",
    label: "Tools & DevOps",
    text: "Git (GitHub, GitLab), CI/CD (Jenkins, Actions, Webhooks), Dynatrace",
  },
  // Data Engineer
  {
    id: "data_engineer_languages",
    type: "data_engineer",
    label: "Languages",
    text: "Python, SQL, Java, Bash, TypeScript, JavaScript",
  },
  {
    id: "data_engineering_etl",
    type: "data_engineer",
    label: "AWS Cloud",
    text: "Lambda, API Gateway, DynamoDB, MariaDB, CLI, S3, SAM (IaC), IAM, CloudFront",
  },
  {
    id: "cloud_infrastructure_aws",
    type: "data_engineer",
    label: "Data Engineering",
    text: "Thread Management & Parallelism (threading/concurrent), Pandas, NumPy, PL/SQL",
  },
  {
    id: "backend_development",
    type: "data_engineer",
    label: "Backend",
    text: "Flask, Spring Boot, FastAPI, REST, PostgreSQL, Oracle, Message and Queue APIs (SQS, SNS, JMS)",
  },
  {
    id: "devops_tools",
    type: "data_engineer",
    label: "DevOps",
    text: "Docker, Linux, CI/CD (Jenkins, GitHub, GitLab), Test-Driven Development (PyTest/JUnit)",
  },

  // Frontend Engineer
  { id: "languages_fe",
    type: "frontend_engineer",
    label: "Languages",
    text: "TypeScript, JavaScript, SQL, Python, Java, Bash, AWS CLI",
  },
  { id: "frameworks_fe",
    type: "frontend_engineer",
    label: "Frameworks",
    text: "React, Next.js, React Native, TanStack (Query, Router, Table), Vue, Svelte, jQuery",
  },
  { id: "cloud_fe",
    type: "frontend_engineer",
    label: "Cloud & Infrastructure",
    text: "AWS (CloudFront, S3, API Gateway, Lambda, SQS, SNS), Linux, Docker, Vite",
  },
  { id: "backend_fe",
    type: "frontend_engineer",
    label: "Backend",
    text: "NoSQL, Spring Boot, FastAPI, Flask, JSP/JSPX, ORM(Hibernate, SQLAlchemy)",
  },
  { id: "component_libraries_fe",
    type: "frontend_engineer",
    label: "Libraries",
    text: "Tailwind CSS, Vanilla Extract, Radix UI, MUI, Headless UI, shadcn/ui, Ant Design, Clsx"
  },
  { id: "apis_fe",
    type: "frontend_engineer",
    label: "APIs & Data",
    text: "REST APIs, OpenAPI, Async Design, Axios, Fetch, Message APIs, OAuth2.0, JWT, OpenID"
  },
  { id: "testing_fe",
    type: "frontend_engineer",
    label: "UX & Testing",
    text: "Dynatrace, User Behavior Analytics, Vitest, React Testing Library, Selenium, Mocks, Stubs",
  },
  { id: "tools_fe",
    type: "frontend_engineer",
    label: "Tools & DevOps",
    text: "Git (GitHub, GitLab), CI/CD (Jenkins, Actions, Webhooks), Figma, Storybook, Agile",
  },
];