/**
 * This file contains the skills section of the resume.
 * 
 * 
 */

export const SKILLS_DATA = [
  // Software Engineer
  { id: "languages",
    type: "default",
    label: "Languages",
    text: "Java, Python, SQL, JavaScript, TypeScript, Bash, PL/SQL",
  },
  { id: "backend",
    type: "default",
    label: "Backend",
    text: "Spring Boot, FastAPI, Flask, AWS Lambda, SQL Alchemy, Pandas, NumPy, Hibernate (JPA)",
  },
  { id: "frontend",
    type: "default",
    label: "Frontend & APIs",
    text:
      "React, AWS API Gateway, AWS CloudFront, Responsive Design, RESTful APIs, OpenAPI/Swagger",
  },
  { id: "data_persistence",
    type: "default",
    label: "Data & Persistence",
    text: "PostgreSQL, Oracle, AWS DynamoDB, AWS S3,  AWS RDS, Data Model Design, Data Normalization",
  },
  { id: "integrations",
    type: "default",
    label: "Integrations",
    text: "JMS, Event-Driven Architecture, Scripting, Batch Processing, ETL Pipelines",
  },
  { id: "security",
    type: "default",
    label: "Security",
    text: "AWS Cognito, AWS VPC, AWS IAM, OAuth2.0, OIDC, JWT",
  },
  { id: "testing",
    type: "default",
    label: "Testing",
    text: "JUnit, Mockito, PyTest, Vitest, Selenium",
  },
  { id: "tools_devops",
    type: "default",
    label: "Tools & DevOps",
    text:
      "Git (GitHub, GitLab), Linux, Docker (Compose), Vite, Maven, Gradle, Jenkins CI/CD, Dynatrace, Rundeck, Agile",
  },
  // Data Engineer
  {
    id: "data_engineer_languages",
    type: "data_engineer",
    label: "Languages",
    text: "Python, SQL, Java, TypeScript, Javascript, Bash",
  },
  {
    id: "data_engineering_etl",
    type: "data_engineer",
    label: "AWS Cloud",
    text: "Lambda, API Gateway, DynamoDB, MariaDB, S3, SAM (IaC), IAM, CloudFront",
  },
  {
    id: "cloud_infrastructure_aws",
    type: "data_engineer",
    label: "Data Engineering",
    text: "Pandas, NumPy, PL/SQL, ETL Pipelines, Event-Driven Architecture",
  },
  {
    id: "backend_development",
    type: "data_engineer",
    label: "Backend",
    text: "Spring Boot, FastAPI, Flask, REST APIs, OAuth2, PostgreSQL, Oracle",
  },
  {
    id: "devops_tools",
    type: "data_engineer",
    label: "DevOps",
    text: "Docker, CI/CD (Jenkins/GitHub), Git, Linux, Unit Testing (PyTest/JUnit)",
  },

  // Frontend Engineer
  { id: "languages_fe",
    type: "frontend_engineer",
    label: "Languages",
    text: "TypeScript, JavaScript, SQL, Python, Java, Bash, AWS CLI",
  },
  { id: "frameworks_fe",
    type: "frontend_engineer",
    label: "Frameworks",
    text: "React, Next.js, React Native, TanStack (Query, Router, Table), Vue, Svelte, jQuery",
  },
  { id: "cloud_fe",
    type: "frontend_engineer",
    label: "Cloud & Infrastructure",
    text: "AWS (CloudFront, S3, API Gateway, Lambda, Cognito), Linux, Docker, Vite",
  },
  { id: "backend_fe",
    type: "frontend_engineer",
    label: "Backend",
    text: "NoSQL, Spring Boot, FastAPI, Flask, JSP/JSPX, ORM(Hibernate, SQLAlchemy)",
  },
  { id: "component_libraries_fe",
    type: "frontend_engineer",
    label: "Libraries",
    text: "Tailwind CSS, Vanilla Extract, Radix UI, MUI, Headless UI, shadcn/ui, Ant Design, Clsx"
  },
  { id: "apis_fe",
    type: "frontend_engineer",
    label: "APIs & Data",
    text: "REST APIs, OpenAPI/Swagger, GraphQL, Axios, Fetch, WebSockets, OAuth2.0, JWT, OpenID Connect"
  },
  { id: "testing_fe",
    type: "frontend_engineer",
    label: "UX & Testing",
    text: "Dynatrace Session Replay, User Behavior Analytics, Vitest, React Testing Library, Selenium, Mocks, Stubs",
  },
  { id: "tools_fe",
    type: "frontend_engineer",
    label: "Tools & DevOps",
    text: "Git (GitHub, GitLab), CI/CD (Jenkins, GitHub Actions, Webhooks), Figma, Storybook, Agile",
  },
];